

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgaudit" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."continents" AS ENUM (
    'Africa',
    'Antarctica',
    'Asia',
    'Europe',
    'Oceania',
    'North America',
    'South America'
);


ALTER TYPE "public"."continents" OWNER TO "postgres";


CREATE TYPE "public"."member_types" AS ENUM (
    'owner',
    'editor',
    'viewer'
);


ALTER TYPE "public"."member_types" OWNER TO "postgres";


CREATE TYPE "public"."profile_types" AS ENUM (
    'editor',
    'contributorviewer'
);


ALTER TYPE "public"."profile_types" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."dbg_update_name_by_email"("p_email" character varying, "p_display_name" character varying) RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$DECLARE
    v_user_id UUID;
BEGIN
    -- Find the user ID by email
    SELECT id INTO v_user_id
    FROM auth.users
    WHERE email = p_email
    LIMIT 1;

    -- If the user exists, update the raw_user_meta_data in auth.users
    IF v_user_id IS NOT NULL THEN
        -- Update the auth.users table
        UPDATE auth.users
        SET raw_user_meta_data = jsonb_build_object(
            'sub', v_user_id,
            'email', p_email,
            'display_name', p_display_name,
            'email_verified', false,
            'phone_verified', false
        )
        WHERE id = v_user_id;

        -- Update the display_name in public.users table
        UPDATE public.users
        SET display_name = p_display_name
        WHERE id = v_user_id;

    ELSE
        RAISE NOTICE 'User with email % not found.', p_email;
    END IF;
END;$$;


ALTER FUNCTION "public"."dbg_update_name_by_email"("p_email" character varying, "p_display_name" character varying) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_editable_user_family_ids"("p_user_id" "uuid") RETURNS TABLE("family_id" integer)
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    RETURN QUERY
    SELECT 
        fu.family_id
    FROM 
        public.family_users fu
    WHERE 
        fu.user_id = p_user_id
        and fu.member_type IN ('owner', 'editor');
END;
$$;


ALTER FUNCTION "public"."get_editable_user_family_ids"("p_user_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_family_ids_for_user"("p_user_id" "uuid") RETURNS TABLE("family_id" integer)
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$BEGIN
    RETURN QUERY
    SELECT 
        fu.family_id
    FROM 
        public.family_users fu
    WHERE 
        fu.user_id = p_user_id;
END;$$;


ALTER FUNCTION "public"."get_family_ids_for_user"("p_user_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.users (id, email, display_name)
  values (new.id, new.email, new.raw_user_meta_data->>'display_name');
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."log_user_id"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  raise notice 'User ID: %', auth.uid();
  return new;
end;
$$;


ALTER FUNCTION "public"."log_user_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_added_by_to_auth_user_id"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$BEGIN
    NEW.added_by := auth.uid();
    RETURN NEW;
END;$$;


ALTER FUNCTION "public"."set_added_by_to_auth_user_id"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."families" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "added_by" "uuid",
    "name" character varying
);


ALTER TABLE "public"."families" OWNER TO "postgres";


ALTER TABLE "public"."families" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."families_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."family_users" (
    "family_id" integer NOT NULL,
    "user_id" "uuid" NOT NULL,
    "member_type" "public"."member_types" NOT NULL
);


ALTER TABLE "public"."family_users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."locations" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "added_by" "uuid",
    "map_reference" character varying,
    "start_date" "date" NOT NULL,
    "end_date" "date",
    "name" "text" NOT NULL,
    "family_id" integer
);


ALTER TABLE "public"."locations" OWNER TO "postgres";


ALTER TABLE "public"."locations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."locations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."moments" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "added_by" "uuid",
    "start_date" "date",
    "end_date" "date",
    "title" "text",
    "body" character varying
);


ALTER TABLE "public"."moments" OWNER TO "postgres";


ALTER TABLE "public"."moments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."moments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pet_moments" (
    "pet_id" integer NOT NULL,
    "moment_id" integer NOT NULL
);


ALTER TABLE "public"."pet_moments" OWNER TO "postgres";


ALTER TABLE "public"."pet_moments" ALTER COLUMN "pet_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pet_moments_pet_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pets" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "added_by" "uuid",
    "name" "text",
    "start_date" "date" NOT NULL,
    "end_date" "date",
    "family_id" integer NOT NULL
);


ALTER TABLE "public"."pets" OWNER TO "postgres";


ALTER TABLE "public"."pets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."photos" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "added_by" "uuid",
    "moment_id" integer,
    "path" "text"
);


ALTER TABLE "public"."photos" OWNER TO "postgres";


ALTER TABLE "public"."photos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."photos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "email" "text",
    "display_name" "text",
    "created_at" time with time zone DEFAULT "now"()
);


ALTER TABLE "public"."users" OWNER TO "postgres";


COMMENT ON TABLE "public"."users" IS 'Profile data for each user.';



COMMENT ON COLUMN "public"."users"."id" IS 'References the internal Supabase Auth user.';



CREATE OR REPLACE VIEW "public"."users_ext" WITH ("security_invoker"='true') AS
 SELECT "u"."id",
    "u"."email",
    "u"."display_name",
    "fu"."family_id",
    "fu"."member_type"
   FROM ("public"."users" "u"
     JOIN "public"."family_users" "fu" ON (("u"."id" = "fu"."user_id")));


ALTER TABLE "public"."users_ext" OWNER TO "postgres";


ALTER TABLE ONLY "public"."families"
    ADD CONSTRAINT "families_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."family_users"
    ADD CONSTRAINT "family_users_pkey" PRIMARY KEY ("family_id", "user_id");



ALTER TABLE ONLY "public"."locations"
    ADD CONSTRAINT "locations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."moments"
    ADD CONSTRAINT "moments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pet_moments"
    ADD CONSTRAINT "pet_moments_pkey" PRIMARY KEY ("pet_id", "moment_id");



ALTER TABLE ONLY "public"."pets"
    ADD CONSTRAINT "pets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."photos"
    ADD CONSTRAINT "photos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "set_added_by_before_insert" BEFORE INSERT ON "public"."families" FOR EACH STATEMENT EXECUTE FUNCTION "public"."set_added_by_to_auth_user_id"();



CREATE OR REPLACE TRIGGER "set_added_by_before_insert" BEFORE INSERT ON "public"."locations" FOR EACH STATEMENT EXECUTE FUNCTION "public"."set_added_by_to_auth_user_id"();



CREATE OR REPLACE TRIGGER "set_added_by_before_insert" BEFORE INSERT ON "public"."moments" FOR EACH STATEMENT EXECUTE FUNCTION "public"."set_added_by_to_auth_user_id"();



CREATE OR REPLACE TRIGGER "set_added_by_before_insert" BEFORE INSERT ON "public"."pets" FOR EACH STATEMENT EXECUTE FUNCTION "public"."set_added_by_to_auth_user_id"();



CREATE OR REPLACE TRIGGER "set_added_by_before_insert" BEFORE INSERT ON "public"."photos" FOR EACH STATEMENT EXECUTE FUNCTION "public"."set_added_by_to_auth_user_id"();



ALTER TABLE ONLY "public"."families"
    ADD CONSTRAINT "families_added_by_fkey" FOREIGN KEY ("added_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."family_users"
    ADD CONSTRAINT "family_users_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id");



ALTER TABLE ONLY "public"."family_users"
    ADD CONSTRAINT "family_users_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."family_users"
    ADD CONSTRAINT "family_users_user_id_fkey1" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."locations"
    ADD CONSTRAINT "locations_added_by_fkey" FOREIGN KEY ("added_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."locations"
    ADD CONSTRAINT "locations_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."moments"
    ADD CONSTRAINT "moments_added_by_fkey" FOREIGN KEY ("added_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."pet_moments"
    ADD CONSTRAINT "pet_moments_moment_id_fkey" FOREIGN KEY ("moment_id") REFERENCES "public"."moments"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pet_moments"
    ADD CONSTRAINT "pet_moments_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."pets"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets"
    ADD CONSTRAINT "pets_added_by_fkey" FOREIGN KEY ("added_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."pets"
    ADD CONSTRAINT "pets_family_id_fkey" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."photos"
    ADD CONSTRAINT "photos_added_by_fkey" FOREIGN KEY ("added_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."photos"
    ADD CONSTRAINT "photos_moment_id_fkey" FOREIGN KEY ("moment_id") REFERENCES "public"."moments"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable ALL based on added_by" ON "public"."families" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "added_by")) WITH CHECK (true);



CREATE POLICY "Enable ALL based on added_by" ON "public"."locations" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "added_by"));



CREATE POLICY "Enable ALL based on added_by" ON "public"."moments" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "added_by"));



CREATE POLICY "Enable ALL based on added_by" ON "public"."pets" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "added_by"));



CREATE POLICY "Enable ALL based on added_by" ON "public"."photos" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "added_by"));



ALTER TABLE "public"."families" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."family_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."locations" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "modifiable_by_editors" ON "public"."families" TO "authenticated" USING (("id" IN ( SELECT "get_editable_user_family_ids"."family_id"
   FROM "public"."get_editable_user_family_ids"("auth"."uid"()) "get_editable_user_family_ids"("family_id"))));



CREATE POLICY "modifiable_by_editors" ON "public"."family_users" TO "authenticated" USING (("family_id" IN ( SELECT "get_editable_user_family_ids"."family_id"
   FROM "public"."get_editable_user_family_ids"("auth"."uid"()) "get_editable_user_family_ids"("family_id"))));



CREATE POLICY "modifiable_by_editors" ON "public"."locations" TO "authenticated" USING (("family_id" IN ( SELECT "get_editable_user_family_ids"."family_id"
   FROM "public"."get_editable_user_family_ids"("auth"."uid"()) "get_editable_user_family_ids"("family_id"))));



CREATE POLICY "modifiable_by_editors" ON "public"."moments" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("public"."pet_moments" "pm"
     JOIN "public"."pets" "fp" ON (("pm"."pet_id" = "fp"."id")))
  WHERE (("pm"."moment_id" = "moments"."id") AND ("fp"."family_id" IN ( SELECT "public"."get_editable_user_family_ids"("auth"."uid"()) AS "get_editable_user_family_ids"))))));



CREATE POLICY "modifiable_by_editors" ON "public"."pets" TO "authenticated" USING (("family_id" IN ( SELECT "get_editable_user_family_ids"."family_id"
   FROM "public"."get_editable_user_family_ids"("auth"."uid"()) "get_editable_user_family_ids"("family_id"))));



CREATE POLICY "modifiable_by_editors" ON "public"."users" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_users" "fu"
  WHERE (("fu"."user_id" = "users"."id") AND ("fu"."family_id" IN ( SELECT "family_users"."family_id"
           FROM "public"."family_users"
          WHERE ("family_users"."user_id" = "auth"."uid"())))))));



ALTER TABLE "public"."moments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pet_moments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."photos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "viewable_by_family" ON "public"."families" FOR SELECT TO "authenticated" USING (("id" IN ( SELECT "public"."get_family_ids_for_user"("auth"."uid"()) AS "get_family_ids_for_user")));



CREATE POLICY "viewable_by_family" ON "public"."family_users" TO "authenticated" USING (("family_id" IN ( SELECT "get_family_ids_for_user"."family_id"
   FROM "public"."get_family_ids_for_user"("auth"."uid"()) "get_family_ids_for_user"("family_id"))));



CREATE POLICY "viewable_by_family" ON "public"."locations" FOR SELECT TO "authenticated" USING (("family_id" IN ( SELECT "public"."get_family_ids_for_user"("auth"."uid"()) AS "get_family_ids_for_user")));



CREATE POLICY "viewable_by_family" ON "public"."moments" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM ("public"."pet_moments" "pm"
     JOIN "public"."pets" "fp" ON (("pm"."pet_id" = "fp"."id")))
  WHERE (("pm"."moment_id" = "moments"."id") AND ("fp"."family_id" IN ( SELECT "public"."get_family_ids_for_user"("auth"."uid"()) AS "get_family_ids_for_user"))))));



CREATE POLICY "viewable_by_family" ON "public"."pet_moments" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."pets" "p"
  WHERE (("pet_moments"."pet_id" = "p"."id") AND ("p"."family_id" IN ( SELECT "get_family_ids_for_user"."family_id"
           FROM "public"."get_family_ids_for_user"("auth"."uid"()) "get_family_ids_for_user"("family_id")))))));



CREATE POLICY "viewable_by_family" ON "public"."pets" FOR SELECT TO "authenticated" USING (("family_id" IN ( SELECT "public"."get_family_ids_for_user"("auth"."uid"()) AS "get_family_ids_for_user")));



CREATE POLICY "viewable_by_family" ON "public"."photos" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM (("public"."moments" "m"
     JOIN "public"."pet_moments" "pm" ON (("m"."id" = "pm"."moment_id")))
     JOIN "public"."pets" "p" ON (("pm"."pet_id" = "p"."id")))
  WHERE (("photos"."moment_id" = "m"."id") AND ("p"."family_id" IN ( SELECT "public"."get_family_ids_for_user"("auth"."uid"()) AS "get_family_ids_for_user"))))));



CREATE POLICY "viewable_by_family" ON "public"."users" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."family_users" "fu"
  WHERE (("fu"."user_id" = "users"."id") AND ("fu"."family_id" IN ( SELECT "family_users"."family_id"
           FROM "public"."family_users"
          WHERE ("family_users"."user_id" = "auth"."uid"())))))));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT ALL ON FUNCTION "public"."dbg_update_name_by_email"("p_email" character varying, "p_display_name" character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."dbg_update_name_by_email"("p_email" character varying, "p_display_name" character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."dbg_update_name_by_email"("p_email" character varying, "p_display_name" character varying) TO "service_role";



GRANT ALL ON FUNCTION "public"."get_editable_user_family_ids"("p_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_editable_user_family_ids"("p_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_editable_user_family_ids"("p_user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."get_family_ids_for_user"("p_user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_family_ids_for_user"("p_user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_family_ids_for_user"("p_user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."log_user_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."log_user_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."log_user_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."set_added_by_to_auth_user_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_added_by_to_auth_user_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_added_by_to_auth_user_id"() TO "service_role";


















GRANT ALL ON TABLE "public"."families" TO "anon";
GRANT ALL ON TABLE "public"."families" TO "authenticated";
GRANT ALL ON TABLE "public"."families" TO "service_role";



GRANT ALL ON SEQUENCE "public"."families_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."families_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."families_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."family_users" TO "anon";
GRANT ALL ON TABLE "public"."family_users" TO "authenticated";
GRANT ALL ON TABLE "public"."family_users" TO "service_role";



GRANT ALL ON TABLE "public"."locations" TO "anon";
GRANT ALL ON TABLE "public"."locations" TO "authenticated";
GRANT ALL ON TABLE "public"."locations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."locations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."moments" TO "anon";
GRANT ALL ON TABLE "public"."moments" TO "authenticated";
GRANT ALL ON TABLE "public"."moments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."moments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."moments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."moments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pet_moments" TO "anon";
GRANT ALL ON TABLE "public"."pet_moments" TO "authenticated";
GRANT ALL ON TABLE "public"."pet_moments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pet_moments_pet_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pet_moments_pet_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pet_moments_pet_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pets" TO "anon";
GRANT ALL ON TABLE "public"."pets" TO "authenticated";
GRANT ALL ON TABLE "public"."pets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."photos" TO "anon";
GRANT ALL ON TABLE "public"."photos" TO "authenticated";
GRANT ALL ON TABLE "public"."photos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."photos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."photos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."photos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";



GRANT ALL ON TABLE "public"."users_ext" TO "anon";
GRANT ALL ON TABLE "public"."users_ext" TO "authenticated";
GRANT ALL ON TABLE "public"."users_ext" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
